<a href="https://colab.research.google.com/github/zilles-vub/real-world-machine-learning/blob/python3/pandas_dataframe_zs.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

In [2]:
miaserie = pd.Series([4, 5, 6.5, 7], index=['first', 'second', 'third', 'fourth'])
miaserie['third']

6.5

In [3]:
miaserie.iloc[2]

6.5

In [4]:
miaserie

first     4.0
second    5.0
third     6.5
fourth    7.0
dtype: float64

In [5]:
type(miaserie.iloc[0])

numpy.float64

In [6]:
s2 = pd.Series([4, 5, 6, 7], index=['first', 'second', 'third', 'fourth'])
s2['third']

6

In [7]:
s3 = pd.Series([4, 5, 'third', 7.0], index=['first', 'second', 'third', 'fourth'])
s3

first         4
second        5
third     third
fourth      7.0
dtype: object

In [8]:
#type(s3.iloc[0])
#type(s3.iloc[2])
type(s3.iloc[-1])

float

In [9]:
s3*2

first              8
second            10
third     thirdthird
fourth          14.0
dtype: object

In [11]:
s2>5

first     False
second    False
third      True
fourth     True
dtype: bool

In [26]:
d = {'one': pd.Series([1., 2., 3.], index=['a', 'b', 'c']),
     'two': pd.Series([1.2, 2.1, 3.5, 4.9], index=['a', 'b', 'c', 'd'])}

In [19]:
nonomog = pd.Series([1, 2, 4.5, 8], index=['a', 2, 3, 'd'])
nonomog

a    1.0
2    2.0
3    4.5
d    8.0
dtype: float64

In [20]:
d

{'one': a    1.0
 b    2.0
 c    3.0
 dtype: float64,
 'two': a    1.0
 b    2.0
 c    3.0
 d    4.0
 dtype: float64}

In [21]:
d['two']+nonomog

2     NaN
3     NaN
a     2.0
b     NaN
c     NaN
d    12.0
dtype: float64

In [22]:
ser1 = pd.Series([1, 2, 3], index=['b', 'a', 'c'])
ser2 = pd.Series([1, 2, 3], index=['a', 'b', 'd'])
ser1 + ser2

a    3.0
b    3.0
c    NaN
d    NaN
dtype: float64

In [28]:
df = pd.DataFrame(d)

In [29]:
df

   one  two
a  1.0  1.2
b  2.0  2.1
c  3.0  3.5
d  NaN  4.9

In [25]:
df2 = pd.DataFrame(ser1 + ser2)
df2

     0
a  3.0
b  3.0
c  NaN
d  NaN

In [30]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4 entries, a to d
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   one     3 non-null      float64
 1   two     4 non-null      float64
dtypes: float64(2)
memory usage: 268.0+ bytes

In [31]:
df['one']

a    1.0
b    2.0
c    3.0
d    NaN
Name: one, dtype: float64

In [35]:
print(df['one'].iloc[0])
df['one']['a']

1.0

1.0

In [ ]:
df['one'] # select by column

a    1.0
b    2.0
c    3.0
d    NaN
Name: one, dtype: float64

In [ ]:
df['one'][0]
df['one']['a']

1.0

In [43]:
df

   one  two
a  1.0  1.2
b  2.0  2.1
c  3.0  3.5
d  NaN  4.9

In [55]:
df.loc['a'] # select by row label

one    1.0
two    1.2
Name: a, dtype: float64

In [56]:
df.iloc[0] # select by column index

one    1.0
two    1.2
Name: a, dtype: float64

In [57]:
df2 = pd.DataFrame(np.random.rand(5, 80))
print(df2)

         0         1         2         3         4         5         6   \
0  0.215288  0.361235  0.380967  0.148923  0.080799  0.537885  0.157919
1  0.614170  0.468499  0.312736  0.888089  0.894824  0.929299  0.575345
2  0.761629  0.222343  0.701367  0.864994  0.246516  0.742250  0.335103
3  0.941525  0.000548  0.108003  0.174733  0.398294  0.897524  0.762559
4  0.784348  0.860691  0.785779  0.702496  0.956993  0.479088  0.710679

         7         8         9   ...        70        71        72        73  \
0  0.165859  0.475999  0.286180  ...  0.292653  0.818828  0.340761  0.203901
1  0.575567  0.556181  0.160614  ...  0.136264  0.600864  0.984860  0.129083
2  0.974070  0.698237  0.860317  ...  0.397905  0.662400  0.722252  0.585836
3  0.965510  0.633607  0.297035  ...  0.930759  0.706613  0.359910  0.625968
4  0.469689  0.397802  0.838061  ...  0.604417  0.647839  0.654136  0.367987

         74        75        76        77        78        79
0  0.531177  0.719093  0.302454  0.035755  0.985769  0.897268
1  0.474686  0.262971  0.464042  0.267760  0.691722  0.466586
2  0.464200  0.917743  0.766035  0.158402  0.024493  0.515662
3  0.023919  0.931682  0.325982  0.121159  0.982866  0.539602
4  0.153486  0.412355  0.204408  0.242691  0.764806  0.699606

[5 rows x 80 columns]

In [58]:
df2[2]

0    0.380967
1    0.312736
2    0.701367
3    0.108003
4    0.785779
Name: 2, dtype: float64

In [59]:
df2.loc[2]

0     0.761629
1     0.222343
2     0.701367
3     0.864994
4     0.246516
        ...
75    0.917743
76    0.766035
77    0.158402
78    0.024493
79    0.515662
Name: 2, Length: 80, dtype: float64

In [60]:
df

   one  two
a  1.0  1.2
b  2.0  2.1
c  3.0  3.5
d  NaN  4.9

In [66]:
df.loc[[False, True, True, False]]

   one  two
b  2.0  2.1
c  3.0  3.5

In [71]:
# select * from df where 'two' > 2
list(df['two']>2)

[False, True, True, True]

In [74]:
# select * from df where 'two' > 2 and 'one' > 2
list((df['two']>2) & (df['one']>2))

[False, False, True, False]

In [62]:
# so[(so['score'] >= 5) & (so['ans_name'] == 'Scott Boston')]
# select row conditional SELECT * FROM DF WHERE ONE > 1 AND TWO < 5
df.loc[(df['one']>1) & (df['two']<5)]

   one  two
b  2.0  2.1
c  3.0  3.5

In [75]:
df

   one  two
a  1.0  1.2
b  2.0  2.1
c  3.0  3.5
d  NaN  4.9

In [78]:
df[df['two']>1.5] # same as before but shorter

   one  two
b  2.0  2.1
c  3.0  3.5
d  NaN  4.9

In [83]:
df['one']

a    1.0
b    2.0
c    3.0
d    NaN
Name: one, dtype: float64

In [82]:
df['one']>1

a    False
b     True
c     True
d    False
Name: one, dtype: bool

In [84]:
df[df['one']>1]

   one  two
b  2.0  2.1
c  3.0  3.5

In [85]:
df[df['one']>1]['two'] # SELECT TWO FROM DF WHERE ONE > 1

b    2.1
c    3.5
Name: two, dtype: float64

In [86]:
#Transpose
df[:].T

       a    b    c    d
one  1.0  2.0  3.0  NaN
two  1.2  2.1  3.5  4.9

In [110]:
df[df['one']>1].T

       b    c
one  2.0  3.0
two  2.1  3.5